# fly.toml app configuration file generated for dating-app-tinder-like-thrumming-sky-8230 on 2024-05-21T21:22:04+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dating-app-tinder-like-thrumming-sky-8230'
primary_region = 'ams'

[build]
  image = 'galamrani/dating-app:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
